services:
  mongo-db:
    image: mongo:7.0.23
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - noc-mongo-data:/data/db
    ports:
      - 27017:27017

volumes:
  noc-mongo-data:
